/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#818CF8',
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
          800: '#3730A3',
          900: '#312E81',
          950: '#1E1B4B',
        },
        accent: {
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          300: '#C4B5FD',
          400: '#A78BFA',
          500: '#8B5CF6',
          600: '#7C3AED',
          700: '#6D28D9',
          800: '#5B21B6',
          900: '#4C1D95',
        },
        glow: {
          cyan: '#22D3EE',
          blue: '#3B82F6',
          violet: '#8B5CF6',
          emerald: '#34D399',
          pink: '#F472B6',
        },
        surface: {
          50: '#1E293B',
          100: '#1A2332',
          200: '#151D2B',
          300: '#111827',
          400: '#0D1321',
          500: '#0A0E1A',
          600: '#070A14',
          700: '#05070F',
          800: '#030509',
          900: '#020304',
        },
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      screens: {
        'xs': '375px',
        '3xl': '1920px',
        '4k': '2560px',
      },
      animation: {
        'aurora': 'aurora 15s ease-in-out infinite',
        'aurora-2': 'aurora-2 12s ease-in-out infinite',
        'aurora-3': 'aurora-3 18s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-slower': 'float 10s ease-in-out infinite',
        'float-reverse': 'float-reverse 7s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'pulse-glow-slow': 'pulse-glow 5s ease-in-out infinite',
        'rotate-ring': 'rotate-ring 20s linear infinite',
        'rotate-ring-reverse': 'rotate-ring-reverse 25s linear infinite',
        'slide-up': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up-delay-1': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.1s forwards',
        'slide-up-delay-2': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.2s forwards',
        'slide-up-delay-3': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.3s forwards',
        'slide-up-delay-4': 'slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.4s forwards',
        'fade-in': 'fade-in 1s ease forwards',
        'fade-in-delay': 'fade-in 1s ease 0.3s forwards',
        'ripple': 'ripple 0.6s linear forwards',
        'particle': 'particle-drift 20s linear infinite',
        'connection-pulse': 'connection-pulse 3s ease-in-out infinite',
        'activity-slide': 'activity-slide 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'gradient-text': 'gradient-text 4s ease infinite',
        'scale-in': 'scale-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'marquee': 'marquee 30s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        aurora: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg) scale(1)', opacity: '0.5' },
          '25%': { transform: 'translate(50px, -30px) rotate(5deg) scale(1.1)', opacity: '0.7' },
          '50%': { transform: 'translate(-20px, 20px) rotate(-3deg) scale(0.95)', opacity: '0.4' },
          '75%': { transform: 'translate(30px, 40px) rotate(7deg) scale(1.05)', opacity: '0.6' },
        },
        'aurora-2': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg) scale(1)', opacity: '0.4' },
          '33%': { transform: 'translate(-40px, 30px) rotate(-5deg) scale(1.15)', opacity: '0.6' },
          '66%': { transform: 'translate(30px, -20px) rotate(3deg) scale(0.9)', opacity: '0.35' },
        },
        'aurora-3': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '0.3' },
          '50%': { transform: 'translate(40px, -40px) rotate(10deg)', opacity: '0.5' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(1deg)' },
        },
        'float-reverse': {
          '0%, 100%': { transform: 'translateY(-20px) rotate(-1deg)' },
          '50%': { transform: 'translateY(0px) rotate(0deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.3), 0 0 40px rgba(139, 92, 246, 0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(99, 102, 241, 0.5), 0 0 60px rgba(139, 92, 246, 0.2)' },
        },
        'rotate-ring': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'rotate-ring-reverse': {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        'particle-drift': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translate(var(--drift-x, 100px), var(--drift-y, -200px)) scale(0.5)', opacity: '0' },
        },
        'connection-pulse': {
          '0%': { strokeDashoffset: '1000', opacity: '0.3' },
          '50%': { opacity: '0.8' },
          '100%': { strokeDashoffset: '0', opacity: '0.3' },
        },
        'activity-slide': {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'gradient-text': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
